const mongoose = require('mongoose');

const colaboradorSchema = new mongoose.Schema({
  tipoDocumento: String,
  numeroDocumento: String,
  apellidoPaterno: String,
  apellidoMaterno: String,
  nombres: String,
  nombreCompleto: String,
  nombreDepositoInterbank: String,
  tipoContrato: String,
  laptop: Boolean,
  gerencia: String,
  cliente: String,
  jefeDirecto: String,
  cargo: String,
  seniority: String,
  fechaIngreso: Date,
  fechaCese: Date,
  periodoPrueba: String,
  sueldo: Number,
  asignacionFamiliar: Boolean,
  costoMensual: Number,
  finContrato: Date,
  diasVencimiento: Number,
  fechaNacimiento: Date,
  edad: Number,
  domicilio: String,
  distrito: String,
  provincia: String,
  departamento: String,
  sexo: String,
  estadoCivil: String,
  nivelEstudios: String,
  carrera: String,
  nacionalidad: String,
  bancoSueldo: String,
  numeroCuentaSueldo: String,
  cciSueldo: String,
  bancoCTS: String,
  cuentaCTS: String,
  cciCTS: String,
  derechohabientes: [String],
  afpOnp: String,
  cussp: String,
  tipoComision: String,
  correoPersonal: String,
  correoCorporativo: String,
  telefono: String
});

module.exports = mongoose.model('Colaborador', colaboradorSchema);
